const aliases = [
  '@aurelia-ux',
  'aurelia-binding',
  'aurelia-dependency-injection',
  'aurelia-dialog',
  'aurelia-event-aggregator',
  'aurelia-framework',
  'aurelia-loader',
  'aurelia-logging',
  'aurelia-metadata',
  'aurelia-notify',
  'aurelia-pal',
  'aurelia-path',
  'aurelia-polyfills',
  'aurelia-resources',
  'aurelia-router',
  'aurelia-store',
  'aurelia-templating',
  'aurelia-templating-resources',
  'aurelia-task-queue',
  'aurelia-validation',
  'awesome-phonenumber',
  'moment',
  'whatwg-fetch',
  'promise-polyfill',
  'tslib',
];

const resources = [
  './controls/ar-tags-input.html',
  './controls/filter-boolean-control.html',
  './controls/filter-chips-control.html',
  './controls/filter-date-control.html',
  './controls/filter-dates-control.html',
  './controls/filter-prompt-control.html',
  './controls/filter-control.html',
  './controls/select-control.html',
  './controls/ux-date-time-picker.html',
  './elements/listing/listing-head.html',
  './elements/listing/listing-list-item.html',
  './elements/listing/listing-list.html',
  './elements/listing/listing-toolbar.html',
  './dialogs/confirm-dialog.html',
  './dialogs/countries-dialog.html',
  './dialogs/languages-dialog.html',
  './dialogs/locales-dialog.html',
  './dialogs/prompt-boolean-dialog.html',
  './dialogs/prompt-select-dialog.html',
  './dialogs/prompt-date-dialog.html',
  './dialogs/prompt-text-dialog.html',
  './elements/ar-breadcrumb-item.html',
  './elements/ar-breadcrumb.html',
  './elements/ar-dialog-prompt.html',
  './elements/ar-dialog.html',
  './elements/ar-drawer.html',
  './elements/ar-lang-selector.html',
  './elements/ar-list-item.html',
  './elements/ar-main-footer.html',
  './elements/ar-main-header.html',
  './elements/ar-metadata.html',
  './elements/ar-next-item.html',
  './elements/ar-next.html',
  './elements/ar-notification.html',
  './elements/ar-option.html',
  './elements/ar-parallax.html',
  './elements/ar-progress.html',
  './elements/ar-range-input.html',
  './elements/ar-search-input.html',
  './elements/ar-select.html',
  './elements/ar-slide.html',
  './elements/ar-slider.html',
  './elements/ar-smart-toolbar.html',
  './elements/ar-spinner-icon.html',
  './elements/ar-spinner-line.html',
  './elements/ar-stripe-element.html',
  './elements/ar-timeline-item.html',
  './elements/ar-timeline.html',
  './elements/ar-video.html',
  './elements/noie.html',
  './elements/ux-input-int-phone.html',
];

const dev = {
  aliases: aliases,
  resources: resources
};

Object.defineProperty(exports, "__esModule", {
  value: true
});

exports.default = dev;

